export { Header } from './Header'
export { Hero } from './Hero'
export { Services } from './Services'
export { Benefits } from './Benefits'
export { Pricing } from './Pricing'
export { CTA } from './CTA'
export { Footer } from './Footer'
